spring:
  datasource:
    dynamic:
      health: true # 健康检测
      primary: localOracle # 默认数据源
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        # 数据源1（本地）
        localOracle:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://mysql:3306/notes?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
        # 数据源2（远程）
        remoteOracle:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://mysql:3306/notes?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456

#  方便调试
logging:
  level:
    mybatis.mate: debug